### ISSUE TITLE
class Database php

### ISSUE THREAD

**Issue by sandub** [wumix/Smart-Space#10]
NOTICE

The space monkeys detected corrupted people on the crew
Maybe it is time to notify your moderator copy-pasting the following error

Message:
Undefined property: Database::$queryCount

File:
/includes/classes/class.Database.php

Line: 75
URL: http://smart-space.esy.es/
PHP-Version: 5.5.35
PHP-API: cgi-fcgi
MySQL-Cleint-Version: 10.0.25-MariaDB

#0 /includes/classes/class.Database.php(75): errorHandler(8, 'Undefined prope...', 'FILEPATH ...', 75, Array)
#1 /includes/classes/Config.class.php(37): Database->query('SELECT * FROM u...')
#2 /includes/common.php(92): Config::init()
#3 /index.php(37): require('FILEPATH ...')
#4 {main}

**Comment by wumix** [comment]
This is tze old smartspace Website.

Use http://smartspace.cu.cc

**Comment by sandub** [comment]
I instal yours script in http://smart-space.esy.es/. Is my site. I update yesterday with all news of yours github update and naw not work.

**Comment by wumix** [comment]
Oh okay i will fix that Problem.

On hostinger you can not edit the standard settings on admin panel hostinger block many settings from the admin.php

**Comment by wumix** [comment]
So I have change the file now you can test it?

**Comment by sandub** [comment]
Work naw! Thanks!

**Comment by wumix** [comment]
super
