### ISSUE TITLE
Proposals!

### ISSUE THREAD

**Issue by sandub** [wumix/Smart-Space#17]
I have several proposals to make the game more attractive.
1. Translation game in as many languages.
2. A referral separate page in which they can make subpages with charts and even referrals monthly competitions with prizes, a market of referrals.
3. Referrals to bring a percentage of producing by their owners as a bonus 10% for example.
4. Thinking about a page shareholding of the game. Let's say 100,000 shares. Shares that can be purchased with Dark Matter (or euro) and collects all game by page Donate to raise a fund to be distributed monthly or when they reach a certain amount eg 100 Euro. From here you can make it so that they can withdraw money from the game in such a way that the game has become and profitable and exciting for the players.

**Comment by sandub** [comment]
5. The game needs banners statistics, and reffereri to promote his online.

**Comment by wumix** [comment]
Hey, hey, so you can make this for us, this game is open source.

Have fun
We are working on this game every day to make this better.
