### ISSUE TITLE
combat simulation not working

### ISSUE THREAD

**Issue by bornhaeusser** [wumix/Smart-Space#2]
after start the simulation only a blank page opens.

**Comment by wumix** [comment]
yes im working on it

**Comment by wumix** [comment]
Hmm on my game smartspace.esy.es is this working.

I have test it with many other battles and it's works.

What ha hosting service you use?

Mfg

**Comment by bornhaeusser** [comment]
Self Hosting.

**Comment by bornhaeusser** [comment]
Had the same in 2 Moons

https://github.com/jkroepke/2Moons/issues/158

**Comment by wumix** [comment]
Ja fixed und läuft jetzt.

Fixed and Working
