### ISSUE TITLE
mobile browser

### ISSUE THREAD

**Issue by bornhaeusser** [wumix/Smart-Space#3]
most thinks are not klickable on a mobile phone (testet on ios with safari and firefox)
both the same.

**Comment by wumix** [comment]
oh okay all tests on my phone with android is working fine i will test it with an iphone.

**Comment by wumix** [comment]
i cant find this problem can anyone help?

**Comment by wumix** [comment]
can you post a link to your game?
And what you can not klick

**Comment by wumix** [comment]
Now on my Brother his iPhone,  Working  it
