### ISSUE TITLE
Bot / forum fix

### ISSUE THREAD

**Issue by adiif1** [wumix/Smart-Space#31]
Hey, please upload bot addon and fix error on forum i can't sign ;/

`POST http://smartgames.esy.es/api/users/6/send-confirmation

<br />
<b>Warning</b>:  escapeshellcmd() has been disabled for security reasons in <b>/home/u825870850/public_html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/MailTransport.php</b> on line <b>259</b><br />
<br />
<b>Fatal error</b>:  Uncaught RuntimeException: Output has been emitted previously; cannot emit response in /home/u825870850/public_html/vendor/zendframework/zend-diactoros/src/Response/SapiEmitterTrait.php:31
Stack trace:
#0 /home/u825870850/public_html/vendor/zendframework/zend-diactoros/src/Response/SapiEmitter.php(27): Zend\Diactoros\Response\SapiEmitter-&gt;assertNoPreviousOutput()
#1 /home/u825870850/public_html/vendor/zendframework/zend-diactoros/src/Server.php(162): Zend\Diactoros\Response\SapiEmitter-&gt;emit(Object(Zend\Diactoros\Response\EmptyResponse))
#2 /home/u825870850/public_html/vendor/flarum/core/src/Http/AbstractServer.php(36): Zend\Diactoros\Server-&gt;listen(Object(Zend\Stratigility\NoopFinalHandler))
#3 /home/u825870850/public_html/api.php(16): Flarum\Http\AbstractServer-&gt;listen()
#4 {main}
  thrown in <b>/home/u825870850/public_html/vendor/zendframework/zend-diactoros/src/Response/SapiEmitterTrait.php</b> on line <b>31</b><br />`

**Comment by wumix** [comment]
Neues forum.

http://SmartGames.square7.ch
