### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by iwnf** [wumix/Smart-Space#32]
Hi :)
I have error with install:

Message: 
Declaration of Database::query($resource) should be compatible with mysqli::query($query, $resultmode = NULL)

File: 
/includes/classes/class.Database.php

Line: 283
URL: http:/xxxxxx.com/
PHP-Version: 7.3.6
PHP-API: apache2handler
MySQL-Cleint-Version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

#0 /includes/common.php(48): errorHandler(2, 'Declaration of ...', 'FILEPATH ...', 283, Array)
#1 /includes/common.php(48): require()
#2 /index.php(37): require('FILEPATH ...')
#3 {main}

Could You help me fix it?

**Comment by wumix** [comment]
Hey you cannot install the script with the installer. You must upload the sql file to your sql and add all informations to your config. Php

**Comment by iwnf** [comment]
@wumix I upload the file and import the sql, edit confit php and I have the error :) I did everything right as in the instruction :)

**Comment by iwnf** [comment]
@wumix i try 3 times, the same error

**Comment by wumix** [comment]
i found your problem change your php version

**Comment by wumix** [comment]
This version needs PHP 5.6.

**Comment by wumix** [comment]
Is fixed
