### ISSUE TITLE
sql database injection

### ISSUE THREAD

**Issue by xteriumboy** [wumix/Smart-Space#5]
this script version is not secure ,please convert all to pdo connection string 

because is not hard to insert some resources into the different planets
thanks

**Comment by wumix** [comment]
On this version is PDO not Planned.

The SM-TEAM will release on http://SmartMoons.xyz the SmartMoons version.

And the SmartMoons will have PDO

**Comment by xteriumboy** [comment]
you have pdo connection game version?
