### ISSUE TITLE
alliance

### ISSUE THREAD

**Issue by wrath76** [wumix/Smart-Space#6]
Hi I keep getting an error when im in the game and i press the alliance tab on the left

Message: 
Undefined variable: topAlly

File: 
/includes/pages/game/class.ShowAlliancePage.php

Line: 213
URL: yyzblog.com/forge/game.php?page=alliance
PHP-Version: 5.6.19
PHP-API: litespeed
MySQL-Cleint-Version: 5.1.59
#0 /includes/pages/game/class.ShowAlliancePage.php(213): errorHandler(8, 'Undefined varia...', 'FILEPATH ...', 213, Array)
#1 /includes/pages/game/class.ShowAlliancePage.php(161): ShowAlliancePage->createSelection()
#2 /game.php(67): ShowAlliancePage->show()
#3 {main}

may you please help
 Edit

**Comment by sandub** [comment]
Message:
Undefined variable: topAlly

File:
/includes/pages/game/class.ShowAlliancePage.php

Line: 213
URL: http://smart-space.esy.es/game.php?page=alliance
PHP-Version: 5.5.35
PHP-API: cgi-fcgi
MySQL-Cleint-Version: 10.0.25-MariaDB

#0 /includes/pages/game/class.ShowAlliancePage.php(213): errorHandler(8, 'Undefined varia...', 'FILEPATH ...', 213, Array)
#1 /includes/pages/game/class.ShowAlliancePage.php(161): ShowAlliancePage->createSelection()
#2 /game.php(67): ShowAlliancePage->show()
#3 {main}

**Comment by wumix** [comment]
Is Fixed
