### ISSUE TITLE
Chat error

### ISSUE THREAD

**Issue by sandub** [wumix/Smart-Space#7]
Fatal error: Uncaught exception 'ErrorException' with message 'Undefined offset: 8192' in /home/u360425568/public_html/includes/GeneralFunctions.php:688 Stack trace: #0 /home/u360425568/public_html/includes/GeneralFunctions.php(688): errorHandler(8, 'Undefined offse...', '/home/u36042556...', 688, Array) #1 [internal function]: exceptionHandler(Object(ErrorException)) #2 {main} thrown in /home/u360425568/public_html/includes/GeneralFunctions.php on line 688

**Comment by wumix** [comment]
yes we working on it.

**Comment by wumix** [comment]
we have fixed the chat error and we will upload it next time
